import type { Metadata } from "next";
import { Poppins } from "next/font/google"; //Roboto import
import "./globals.css";
import AuthProvider from '../app/DataProvider/AuthProvider/AuthProvider'
import ProfileProvider from '../app/DataProvider/ProfileDataProvider/ProfileProvider'
// Roboto font setup
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <ProfileProvider>
        {children}
        </ProfileProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
